"use client";
import { useState } from "react";
type Log = { id: number; channel: string; recipient: string; status: string; error: string; eventName: string; customerName: string; createdAt: string; ticketLink: string };
export default function DeliveryAdmin({ initialSettings, logs }: { initialSettings: { enabled: boolean; configured: boolean }; logs: Log[] }) {
  const [enabled, setEnabled] = useState(initialSettings.enabled); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function save() { setSaving(true); const response = await fetch("/api/admin/delivery-settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled }) }); const result = await response.json(); setMessage(response.ok ? "SMS setting saved." : result.error || "Could not save setting."); setSaving(false); }
  async function resend(log: Log, channel: "sms" | "email") { setMessage(""); const response = await fetch("/api/ticket-delivery/resend", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketLink: log.ticketLink, channel }) }); const result = await response.json(); setMessage(result.message || result.error || "Resend finished."); }
  return <div className="delivery-admin-grid"><section className="lp-card"><h2>SMS delivery</h2><div className={`storage-status ${initialSettings.configured ? "is-ready" : "is-blocked"}`}><strong>{initialSettings.configured ? "Twilio configured" : "Twilio not configured"}</strong><span>{initialSettings.configured ? "Credentials are available only to the server." : "Add all three TWILIO variables in Render before enabling SMS."}</span></div><label className="delivery-toggle"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} /> Enable transactional ticket texts</label><button className="lp-button" onClick={save} disabled={saving || (enabled && !initialSettings.configured)}>{saving ? "Saving…" : "Save SMS Setting"}</button>{message ? <p className="ai-settings-copy">{message}</p> : null}<small>Texts contain one secure order link and include STOP/HELP instructions. Credentials are never returned to the browser.</small></section>
  <section className="lp-card delivery-log-card"><h2>Delivery logs</h2>{logs.length ? <div className="delivery-log-list">{logs.map(log => <article key={log.id}><div><strong>{log.channel.toUpperCase()} — {log.status}</strong><span>{log.eventName || "Ticket delivery"} · {log.customerName || "Guest"}</span><span>{log.recipient} · {new Date(log.createdAt).toLocaleString()}</span>{log.error ? <small>{log.error}</small> : null}</div>{log.ticketLink ? <div className="delivery-log-actions"><a href={log.ticketLink} target="_blank" rel="noreferrer">Display</a><button onClick={() => navigator.clipboard.writeText(`${window.location.origin}${log.ticketLink}`)}>Copy link</button><button onClick={() => resend(log, "sms")}>Resend text</button><button onClick={() => resend(log, "email")}>Resend email</button></div> : null}</article>)}</div> : <p>No delivery attempts have been logged yet.</p>}</section></div>;
}
