"use client";
import { useMemo,useState } from "react";

type Row={user_id:number;name:string|null;email:string;status:string;display_status:string;stripe_customer_id:string|null;stripe_subscription_id:string|null;trial_end:string|null;grace_ends_at:string|null;current_period_end:string|null;cancel_at_period_end:number};
export default function SubscriptionTable({rows}:{rows:Row[]}){
 const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [message,setMessage]=useState("");
 const shown=useMemo(()=>rows.filter(r=>(filter==="all"||r.display_status===filter)&&`${r.name} ${r.email}`.toLowerCase().includes(query.toLowerCase())),[rows,query,filter]);
 async function grace(userId:number,days:number){setMessage("Saving…");const res=await fetch("/api/admin/subscriptions/grace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,days})});const data=await res.json();if(!res.ok){setMessage(data.error||"Unable to update grace.");return}setMessage("Grace updated. Refreshing…");location.reload();}
 return <><div style={{display:"flex",gap:10,flexWrap:"wrap",margin:"18px 0"}}><input aria-label="Search promoters" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)} style={input}/><select value={filter} onChange={e=>setFilter(e.target.value)} style={input}><option value="all">All statuses</option>{["active","trialing","grace_period","past_due","canceled","expired","none"].map(x=><option key={x}>{x}</option>)}</select></div>{message&&<p role="status">{message}</p>}
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{["Promoter","Status","Trial / grace","Next billing","Stripe","Actions"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{shown.map(r=><tr key={r.user_id}><td style={td}><strong>{r.name||"Promoter"}</strong><br/><span style={{color:"#94a3b8"}}>{r.email}</span></td><td style={td}>{r.display_status.replaceAll("_"," ")}{r.cancel_at_period_end?" · ending":""}</td><td style={td}>{fmt(r.trial_end||r.grace_ends_at)}</td><td style={td}>{fmt(r.current_period_end)}</td><td style={td}>{r.stripe_customer_id?<a href={`https://dashboard.stripe.com/customers/${r.stripe_customer_id}`} target="_blank" rel="noreferrer" style={{color:"#67e8f9"}}>Open customer</a>:"—"}<br/><small>{r.stripe_subscription_id||""}</small></td><td style={td}><button onClick={()=>grace(r.user_id,30)} style={button}>+30 days</button> <button onClick={()=>grace(r.user_id,0)} style={button}>End grace</button><br/><a href={`/admin/users?search=${encodeURIComponent(r.email)}`} style={{color:"#67e8f9"}}>View promoter</a></td></tr>)}</tbody></table></div></>;
}
function fmt(v:string|null){return v?new Date(v).toLocaleDateString():"—"} const input:React.CSSProperties={padding:12,borderRadius:10,border:"1px solid #475569",background:"#fff",color:"#0f172a",minWidth:220}; const th:React.CSSProperties={textAlign:"left",padding:12,borderBottom:"1px solid #475569"}; const td:React.CSSProperties={padding:12,borderBottom:"1px solid #334155",verticalAlign:"top"}; const button:React.CSSProperties={padding:"7px 9px",marginBottom:8,borderRadius:8,border:"1px solid #475569",background:"#1e293b",color:"white",cursor:"pointer"};
